apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-17T07:20:30Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "8266"
  uid: ffa43c76-bcf5-4872-84a0-189aed107ed3
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.100.86.105
  clusterIPs:
  - 10.100.86.105
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32307
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
